### ISSUE TITLE
Java 1.8 issue

### ISSUE THREAD

**Issue by Mihirsur007** [0rang-3/PaintJ#2]
How do I download java 1.8 sdk?

**Comment by ruhanpandit** [comment]
To download Java 1.8 SDK:

1. Go to: `File > New > Project` to create a new project
2. Under JDK, click the current JDK and press "Download JDK"
3. For Version, select 1.8 (NOT 18). For Vender, select "Amazon Corrento".
4. Press Download, and then Create
